### ISSUE TITLE
Possible bug in EVM output

### ISSUE THREAD

**Issue by asedlmayr** [Agora-wireless/Agora#401]
EVM appears to be reporting a value that is to low.  Tested with all UL frame.  Need to add a sqrt?

**Comment by tingjunchen** [comment]
Yes, I think so. We went through the code, it's likely that a sqrt needs to be added (so sqrt of the averaged 2-norm between measured and ground truth constellations)

**Comment by asedlmayr** [comment]
Fixed in PR #405
